### Milestone: Portfolio details popup window
ibrahim777764/new_portfolio pull request #11
Opened 2022-03-09 19:13 UTC by ibrahim777764

### Milestone: Portfolio details popup window

- Use basic JavaScript syntax.
- Use JavaScript to manipulate DOM elements.
- Use JavaScript events.
- understood how to parse a Figma design to create a UI.
- Use objects to store and access data.

2022-03-09 19:15 UTC, ibrahim777764 commented
please review my code,thankyou

2022-03-09 19:29 UTC, gemmen29 requested changes
Hi @ibrahim777764, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-09 19:29 UTC, gemmen29 commented on index.js
> +// });
Kindly get rid of the comments in order to make your code cleaner.

2022-03-09 19:29 UTC, gemmen29 commented on index.js
> +  });
Kindly try to match the `see live` and `see source` in the desktop version width `992px` to match the Figma design. 
| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/157516392-9a86fe29-dc76-4731-8790-ec74ec576b2a.png) | ![image](https://user-images.githubusercontent.com/24703171/157516259-73649f7e-b706-4227-86f9-d413b3d9d195.png) |
the text and icon should be beside each other.

2022-03-09 19:29 UTC, gemmen29 commented on index.js
> +  });
Kindly add the scroll for the details modal in mobile version width `375px` in order all your modal content appear.
![image](https://user-images.githubusercontent.com/24703171/157516954-3acddadc-5ec6-4c38-8849-cfe4bdf9b725.png)

2022-03-10 09:43 UTC, ibrahim777764 commented
completed all required changes,hope so every thing is ok now ,thankyou

2022-03-10 09:56 UTC, ShoiraTa requested changes
Hi @ibrahim777764 ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-10 09:56 UTC, ShoiraTa commented on index.html
> +                        <img alt="icon" class="icon-btn" src="gitexp.png" />
- [ ] Please make sure that in mobile view the content inside the buttons does not wrap: 

<img width="338" alt="Screenshot 2022-03-10 at 13 48 32" src="https://user-images.githubusercontent.com/77038610/157635931-c5172803-ac86-4d69-8bb2-63c4e35e716d.png">
 You can achieve that by decreasing the font size, deleting the letter spacing, and decreasing the padding. 
Try this: 

```
.popup-button-group > .btn-popup {
    font-size: 15px;
    letter-spacing: 0;
    justify-content: center;
    align-items: center;
}
```

2022-03-10 09:56 UTC, ShoiraTa commented on index.html
> +  <div class="modal-content">
- [ ] OPTIONAL:  I can see lots of commented code here, if you do not need it anymore lets delete it and make sure that the project is clean and professional

2022-03-10 09:56 UTC, ShoiraTa commented on index.js
> +  });
- [ ] As the previous reviewer mentioned, make sure that the text and icon are beside each other. They are still wrapping: 
<img width="277" alt="Screenshot 2022-03-10 at 13 54 32" src="https://user-images.githubusercontent.com/77038610/157637022-f74b1345-9805-4cd7-943c-072ad3d15743.png">

Try this:
```
button {
font-size: 15px;
letter-spacing: 0px;
}
```

2022-03-10 12:40 UTC, ibrahim777764 commented
please review my code , thankyou

2022-03-10 12:46 UTC, elyor-doniyorov approved these changes
Hi @ibrahim777764, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-10 12:47 UTC, merged