Milestone desktop website
ibrahim777764/new_portfolio pull request #7
Opened 2022-02-24 11:32 UTC by ibrahim777764

### Milestone:Portfolio: desktop version 

- understood how to create Is adaptable to different screen sizes using media queries. 
- understood how to parse a Figma design to create a UI

2022-02-24 11:35 UTC, ibrahim777764 commented
please review my code, let me know if there is any changes.thankyou

2022-02-24 12:04 UTC, Deepakdanger requested changes
Hi @ibrahim777764, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-24 12:04 UTC, Deepakdanger commented on index.html
>      <header>
- [ ] While doing the **desktop version**, you mismatch the **mobile version** of the header section. Kindly fix that.
- Your website
![fdbfbdf](https://user-images.githubusercontent.com/26767383/155520030-2ec7dbd6-e495-49e3-a7fe-c85094b66f44.PNG)
- Figma Design 
![nfgnfgn](https://user-images.githubusercontent.com/26767383/155520068-9d640feb-0c6d-4170-aa89-d9d7782813d0.PNG)

2022-02-24 12:04 UTC, Deepakdanger commented on index.html
> +    <section class="container-flex about-myself" id="about-myself-id">
- [ ] While doing the **desktop version**, you mismatch the **mobile version** of the `About me` section. Kindly fix that.
- Your website

![sdvdv](https://user-images.githubusercontent.com/26767383/155520356-52076e36-4e12-4878-b72a-e6afa65f2c34.PNG)

- Figma website

![dbfdfbd](https://user-images.githubusercontent.com/26767383/155520403-3d24f825-e8b2-496c-9728-a9420f555fcb.PNG)

2022-02-25 11:01 UTC, ibrahim777764 commented
### Updated all required changes

please review my code thankyou

2022-02-25 12:37 UTC, medaminedev66 approved these changes
Hi @ibrahim777764 , 

# Status: Approved ✔️
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-25 12:47 UTC, merged